openapi: 3.0.3
info: { title: JYBank API, version: v1 }
servers: [ { url: http://localhost:8080 } ]
paths:
  /v1/transfers:
    post:
      summary: Create transfer
      security: [ { bearerAuth: [] } ]
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferCreateReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferCreateRes'
components:
  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
  schemas:
    TransferCreateReq:
      type: object
      required: [sourceWalletId, destWalletId, amount, idemKey]
      properties:
        sourceWalletId: { type: integer, format: int64 }
        destWalletId: { type: integer, format: int64 }
        amount: { type: integer }
        memo: { type: string }
        idemKey: { type: string }
    TransferCreateRes:
      type: object
      properties:
        transferId: { type: integer, format: int64 }
        status: { type: string }